version: '3.8'

services:
  mcpd:
    build: ./mcpd
    container_name: itex-mcpd
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CEO_PUBLIC_KEY_PATH=/app/certs/ceo_public.pem
      - MCP_PRIVATE_KEY_PATH=/app/certs/mcp_private.key
      - LOG_LEVEN=info
      - TELEGRAM_BOT_TOKEN=$ŠTELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEDPAM_CHAT_ID}
    networks:
      - itex-network

  redis:
    image: redis:alpine
    container_name: itex-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - itex-network

  watchtower:
    image: containrr/watchtower
    container_name: itex-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup
    networks:
      - itex-network

networks:
  itex-network:
    driver: bridge

volumes:
  redis-data: